[package]
name = "hesai-pcap-parser-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdf5 = { git = "https://github.com/aldanor/hdf5-rust.git" }
ndarray = "0.15.6"
pcap-parser = "0.14.0"
